settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: src
  path: /go/src
  commands: 
    install:
      status: true
      method: sh .realize.sh
    run:
      status: true
      method: /go/src/main
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor