basePath: /
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: APIサポーター
    url: http://www.swagger.io/support
  description: 仕様書に関する内容説明
  license:
    name: ライセンス(必須)
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: 仕様書使用する際の注意事項
  title: members-api
  version: バージョン(1.0)
paths: {}
swagger: "2.0"
