basePath: /api/v1
definitions:
  repository.UserRepository:
    type: object
host: localhost:8000
info:
  contact:
    email: tochika.biz@gmail.com
    name: hiwatee
    url: https://github.com/hiwatee
  description: メンバーズAPI
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://github.com/hiwatee/gin-members-api
  title: メンバーズAPI
  version: "1.0"
paths:
  /users:
    get:
      description: ユーザー一覧取得API
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repository.UserRepository'
    post:
      description: ユーザー一覧取得API
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repository.UserRepository'
swagger: "2.0"
