basePath: /api/v1
definitions:
  controllers.UserCreateRequest:
    properties:
      email:
        example: info@example.com
        type: string
      password:
        example: password2021
        type: string
    type: object
  controllers.UserResponse:
    properties:
      createdAt:
        example: "2021-01-10T15:42:36+09:00"
        type: string
      email:
        example: info@example.com
        type: string
      id:
        example: 1
        type: integer
      updatedAt:
        example: "2021-01-10T15:42:36+09:00"
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: tochika.biz@gmail.com
    name: hiwatee
    url: https://github.com/hiwatee
  description: メンバーズAPI
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://github.com/hiwatee/gin-members-api
  title: メンバーズAPI
  version: "1.0"
paths:
  /registration:
    post:
      description: ユーザー一覧取得API
      parameters:
      - description: User Create Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controllers.UserCreateRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.UserResponse'
  /users:
    get:
      description: ユーザー一覧取得API
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.UserResponse'
  /users/{id}:
    get:
      description: ユーザー詳細情報API
      parameters:
      - description: The key for user
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.UserResponse'
swagger: "2.0"
